<#
.SYNOPSIS
    Write win_shell into $PROFILE so new terminals load the prompt and drop conflicting aliases.

.DESCRIPTION
    1. Create $PROFILE if it does not exist
    2. Insert or update a marked block that dotsources this repo's load.ps1
    3. Run load.ps1 now: UTF-8, prompt, session PATH, remove aliases

.EXAMPLE
    .\powershell\build.ps1
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$markerBegin = '# >>> win_shell BEGIN'
$markerEnd   = '# <<< win_shell END'

$psDir      = $PSScriptRoot
$repoRoot   = Split-Path -Parent $psDir
$loadScript = Join-Path $psDir 'load.ps1'

if (-not (Test-Path -LiteralPath $loadScript)) {
    throw "load.ps1 not found: $loadScript"
}
if (-not $PROFILE) {
    throw '$PROFILE is not defined, cannot install.'
}

$profileDir = Split-Path -Parent $PROFILE
$profileCreated = $false
if (-not (Test-Path -LiteralPath $PROFILE)) {
    if ($profileDir -and -not (Test-Path -LiteralPath $profileDir)) {
        New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
    }
    New-Item -ItemType File -Path $PROFILE -Force | Out-Null
    $profileCreated = $true
}

Write-Host "repo:    $repoRoot"
Write-Host "profile: $PROFILE"
if ($profileCreated) {
    Write-Host ''
    Write-Host ('=' * 60) -ForegroundColor Yellow
    Write-Host '  $PROFILE not found, automatically created:' -ForegroundColor Black -BackgroundColor Yellow
    Write-Host "  $PROFILE" -ForegroundColor Black -BackgroundColor Yellow
    Write-Host ('=' * 60) -ForegroundColor Yellow
} else {
    Write-Host 'profile file status: already exists' -ForegroundColor DarkGray
}

$escapedLoad = $loadScript.Replace("'", "''")
$block = @(
    $markerBegin
    '# generated by build.ps1; run build.ps1 again to update'
    ". '$escapedLoad'"
    $markerEnd
)

$out = [System.Collections.Generic.List[string]]::new()
$skip = $false
$replaced = $false
foreach ($line in @(Get-Content -LiteralPath $PROFILE -ErrorAction SilentlyContinue)) {
    if ($line -eq $markerBegin) {
        $skip = $true
        foreach ($bl in $block) { $out.Add($bl) }
        $replaced = $true
        continue
    }
    if ($skip) {
        if ($line -eq $markerEnd) { $skip = $false }
        continue
    }
    $out.Add($line)
}
if (-not $replaced) {
    if ($out.Count -gt 0 -and $out[$out.Count - 1] -ne '') {
        $out.Add('')
    }
    foreach ($bl in $block) { $out.Add($bl) }
}

Set-Content -LiteralPath $PROFILE -Value ($out -join [Environment]::NewLine) -Encoding UTF8
Write-Host $(if ($replaced) { "updated win_shell block in `$PROFILE" } else { "appended win_shell block to `$PROFILE" })

. $loadScript
Write-Host "loaded current session (prompt + aliases + session PATH)"
Write-Host 'done. new terminals will run load.ps1 via $PROFILE.'
