<#
.SYNOPSIS
    Install win_shell next to $PROFILE and hook it for new terminals.

.DESCRIPTION
    1. Create $PROFILE if it does not exist
    2. Copy load.ps1 and prompt\ to <PROFILE-DIR>\win_shell\
    3. Record this repo's bin\ in bin.path so commands still resolve
    4. Write a marked block that dotsources the installed copy, not the repo
    5. Run the installed load.ps1 now

.EXAMPLE
    .\powershell\build.ps1
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$markerBegin = '# >>> win_shell BEGIN'
$markerEnd   = '# <<< win_shell END'

$psDir      = $PSScriptRoot # 当前build.ps1的脚本位置
$repoRoot   = Split-Path -Parent $psDir 
$srcLoad    = Join-Path $psDir 'load.ps1'
$srcPrompt  = Join-Path $psDir 'prompt'
$repoBin    = Join-Path $repoRoot 'bin'

if (-not (Test-Path -LiteralPath $srcLoad)) {
    throw "load.ps1 not found: $srcLoad"
}
if (-not (Test-Path -LiteralPath $srcPrompt)) {
    throw "prompt directory not found: $srcPrompt"
}
if (-not $PROFILE) {
    throw '$PROFILE is not defined, cannot install.'
}

$profileDir = Split-Path -Parent $PROFILE
$profileCreated = $false
if (-not (Test-Path -LiteralPath $PROFILE)) {
    if ($profileDir -and -not (Test-Path -LiteralPath $profileDir)) {
        New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
    }
    New-Item -ItemType File -Path $PROFILE -Force | Out-Null
    $profileCreated = $true
}

$installDir  = Join-Path $profileDir 'win_shell'
$destPrompt  = Join-Path $installDir 'prompt'
$loadScript  = Join-Path $installDir 'load.ps1'
$binPathFile = Join-Path $installDir 'bin.path'

New-Item -ItemType Directory -Path $installDir -Force | Out-Null
Copy-Item -LiteralPath $srcLoad -Destination $loadScript -Force
if (Test-Path -LiteralPath $destPrompt) {
    Remove-Item -LiteralPath $destPrompt -Recurse -Force
}
Copy-Item -LiteralPath $srcPrompt -Destination $destPrompt -Recurse -Force
Set-Content -LiteralPath $binPathFile -Value ([IO.Path]::GetFullPath($repoBin)) -Encoding UTF8

Write-Host "repo:     $repoRoot"
Write-Host "profile:  $PROFILE"
Write-Host "install:  $installDir"
if ($profileCreated) {
    Write-Host ''
    Write-Host ('=' * 60) -ForegroundColor Yellow
    Write-Host '  $PROFILE not found, automatically created:' -ForegroundColor Black -BackgroundColor Yellow
    Write-Host "  $PROFILE" -ForegroundColor Black -BackgroundColor Yellow
    Write-Host ('=' * 60) -ForegroundColor Yellow
} else {
    Write-Host 'profile file status: already exists' -ForegroundColor DarkGray
}

$escapedLoad = $loadScript.Replace("'", "''")
$block = @(
    $markerBegin
    '# generated by build.ps1; dotsources the copy next to $PROFILE'
    ". '$escapedLoad'"
    $markerEnd
)

$out = [System.Collections.Generic.List[string]]::new()
$skip = $false
$replaced = $false
foreach ($line in @(Get-Content -LiteralPath $PROFILE -ErrorAction SilentlyContinue)) {
    if ($line -eq $markerBegin) {
        $skip = $true
        foreach ($bl in $block) { $out.Add($bl) }
        $replaced = $true
        continue
    }
    if ($skip) {
        if ($line -eq $markerEnd) { $skip = $false }
        continue
    }
    $out.Add($line)
}
if (-not $replaced) {
    if ($out.Count -gt 0 -and $out[$out.Count - 1] -ne '') {
        $out.Add('')
    }
    foreach ($bl in $block) { $out.Add($bl) }
}

Set-Content -LiteralPath $PROFILE -Value ($out -join [Environment]::NewLine) -Encoding UTF8
Write-Host $(if ($replaced) { "updated win_shell block in `$PROFILE" } else { "appended win_shell block to `$PROFILE" })
Write-Host "copied prompt + load.ps1 to $installDir"

. $loadScript
Write-Host "loaded current session (prompt + aliases + session PATH)"
Write-Host 'done. new terminals will run the installed load.ps1 via $PROFILE.'
